DROP TABLE IF EXISTS WORD_DICTIONARY;

CREATE TABLE WORD_DICTIONARY(
  ID VARCHAR(6) NOT NULL
  , WORD VARCHAR(50) NOT NULL
  , MEANING VARCHAR(5000) NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY(id)
);